-- Test the left/right keys
test.open('words.txt')
local lineno = test.lineno
local colno = test.colno
local assertEq = test.assertEq
test.key('j', 'l')
assertEq(colno(), 1) assertEq(lineno(), 1)
-- Check w
test.key('w')
assertEq(colno(), 4) assertEq(lineno(), 1)
test.key('w')
assertEq(colno(), 8) assertEq(lineno(), 1)
test.key('w')
assertEq(colno(), 12) assertEq(lineno(), 1)
test.key('w')
assertEq(colno(), 16) assertEq(lineno(), 1)
test.key('w')
assertEq(colno(), 19) assertEq(lineno(), 1)
test.key('w')
assertEq(colno(), 0) assertEq(lineno(), 2)
test.key('w')
assertEq(colno(), 5) assertEq(lineno(), 2)
test.key('w')
assertEq(colno(), 19) assertEq(lineno(), 2)
test.key('w')
assertEq(colno(), 22) assertEq(lineno(), 2)
-- now check b
test.key('b')
assertEq(colno(), 19) assertEq(lineno(), 2)
test.key('b')
assertEq(colno(), 5) assertEq(lineno(), 2)
test.key('b')
assertEq(colno(), 0) assertEq(lineno(), 2)
test.key('b')
assertEq(colno(), 19) assertEq(lineno(), 1)
test.key('b')
assertEq(colno(), 16) assertEq(lineno(), 1)
test.key('b')
assertEq(colno(), 12) assertEq(lineno(), 1)
test.key('b')
assertEq(colno(), 8) assertEq(lineno(), 1)
test.key('b')
assertEq(colno(), 4) assertEq(lineno(), 1)
test.key('b')
assertEq(colno(), 0) assertEq(lineno(), 1)
-- now test e
test.key('e')
assertEq(colno(), 2) assertEq(lineno(), 1)
test.key('e')
assertEq(colno(), 6) assertEq(lineno(), 1)
test.key('e')
assertEq(colno(), 10) assertEq(lineno(), 1)
test.key('e')
assertEq(colno(), 14) assertEq(lineno(), 1)
test.key('e')
assertEq(colno(), 17) assertEq(lineno(), 1)
test.key('e')
assertEq(colno(), 21) assertEq(lineno(), 1)
test.key('e')
assertEq(colno(), 3) assertEq(lineno(), 2)
test.key('e')
assertEq(colno(), 17) assertEq(lineno(), 2)
test.key('e')
assertEq(colno(), 22) assertEq(lineno(), 2)
test.key('e')
assertEq(colno(), 22) assertEq(lineno(), 2)

-- Test using the motion as part of an action
test.key('2', 'G', 'w')
test.key('d', 'e')
assertEq(lineno(), 1)
assertEq(colno(), 4)
assertEq(buffer:get_line(2), 'hey  cee dee ee eff\n')
